baseurl = "https://mickael-salmon.github.io/"
title = "Mickaël Salmon"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "Mickaël"

[markup.highlight]
style = "github-dark"

[params]
  author = "Mickaël Salmon"
  info = "IT Manager"
  description = "Portfolio"
  keywords = "blog,developer,it, security, scripts, doc, personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "mail@mickael-salmon.ch"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/mickael-salmon/"

# Menu links
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 2

  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Readings"
    url = "/readings/"
    weight = 5

  [[menu.main]]
    name = "Scripts"
    url = "/scripts/"
    weight = 6
